# -*- coding: utf-8 -*-
"""Dashboard Martez

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ng4xTHeT2I-8zI_xr8mNy9-et6jCutkM
"""


import pandas as pd
#import numpy as np
import dash
from dash import html
from dash import dcc
#import dash_bootstrap_components as dbc
#from dash.dependencies import Input, Output
import plotly.express as px
import plotly.io as pio
pio.renderers.default='browser'


#Initializing our application
app = dash.Dash(__name__)
df = pd.read_csv("C:/Users/Diana Valladares/Documents/GitHub/Python-Projects/KPI 2022 Goals .csv")
df.head()
df.dropna(axis = 1, how = 'all', inplace=True)

# =============================================================================
# #dropping all unecassry columns
# """ EDA """
# =============================================================================

df['Total Transfers '] =df['Total Transfers '].replace({"215 so far": 215})
df['Total Applications'] = df['Total Applications'].replace({'25 so far':25})
df['Workable Total Transfers  (MQL)'] =df['Workable Total Transfers  (MQL)'].replace({"161 so far": 161})
df['Total Applications  (UQL)'] =df['Total Applications  (UQL)'].replace({"25 so far": 25})
df.drop(columns='Total Applications', inplace = True)
print(df.value_counts())


# =============================================================================
# #Creating Dashboard
# =============================================================================


fig = px.scatter(df, x='Total Transfers ', y= 'Year 2022 Month', log_x=True, size='Total Transfer Conversion % ', color='Workable Total Transfer Conversion % ')
app.layout = html.Div([dcc.Graph(id="Operation Graduate KPI", figure=fig)])
fig.show()

